//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWMS.WinService.BusinessServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com/oracle/apps/cuxwms/Cuxwms.wsdl", ConfigurationName="BusinessServices.cuxwms")]
    public interface cuxwms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com/oracle/apps/cuxwms/Cuxwms.wsdl/invokews", ReplyAction="*")]
        EWMS.WinService.BusinessServices.invokewsResponse invokews(EWMS.WinService.BusinessServices.invokewsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://com/oracle/apps/cuxwms/Cuxwms.wsdl/invokews", ReplyAction="*")]
        System.Threading.Tasks.Task<EWMS.WinService.BusinessServices.invokewsResponse> invokewsAsync(EWMS.WinService.BusinessServices.invokewsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokews", WrapperNamespace="http://com/oracle/apps/cuxwms/Cuxwms.wsdl", IsWrapped=true)]
    public partial class invokewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string pIfaceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pBatchNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pRequestData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xReturnCode_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string xReturnMesg_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string xResponseData_out;
        
        public invokewsRequest() {
        }
        
        public invokewsRequest(string pIfaceCode, string pBatchNumber, string pRequestData, string xReturnCode_out, string xReturnMesg_out, string xResponseData_out) {
            this.pIfaceCode = pIfaceCode;
            this.pBatchNumber = pBatchNumber;
            this.pRequestData = pRequestData;
            this.xReturnCode_out = xReturnCode_out;
            this.xReturnMesg_out = xReturnMesg_out;
            this.xResponseData_out = xResponseData_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokewsResponse", WrapperNamespace="http://com/oracle/apps/cuxwms/Cuxwms.wsdl", IsWrapped=true)]
    public partial class invokewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xReturnCode_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xReturnMesg_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xResponseData_out;
        
        public invokewsResponse() {
        }
        
        public invokewsResponse(string xReturnCode_out, string xReturnMesg_out, string xResponseData_out) {
            this.xReturnCode_out = xReturnCode_out;
            this.xReturnMesg_out = xReturnMesg_out;
            this.xResponseData_out = xResponseData_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cuxwmsChannel : EWMS.WinService.BusinessServices.cuxwms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cuxwmsClient : System.ServiceModel.ClientBase<EWMS.WinService.BusinessServices.cuxwms>, EWMS.WinService.BusinessServices.cuxwms {
        
        public cuxwmsClient() {
        }
        
        public cuxwmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cuxwmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cuxwmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cuxwmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWMS.WinService.BusinessServices.invokewsResponse EWMS.WinService.BusinessServices.cuxwms.invokews(EWMS.WinService.BusinessServices.invokewsRequest request) {
            return base.Channel.invokews(request);
        }
        
        public void invokews(string pIfaceCode, string pBatchNumber, string pRequestData, ref string xReturnCode_out, ref string xReturnMesg_out, ref string xResponseData_out) {
            EWMS.WinService.BusinessServices.invokewsRequest inValue = new EWMS.WinService.BusinessServices.invokewsRequest();
            inValue.pIfaceCode = pIfaceCode;
            inValue.pBatchNumber = pBatchNumber;
            inValue.pRequestData = pRequestData;
            inValue.xReturnCode_out = xReturnCode_out;
            inValue.xReturnMesg_out = xReturnMesg_out;
            inValue.xResponseData_out = xResponseData_out;
            EWMS.WinService.BusinessServices.invokewsResponse retVal = ((EWMS.WinService.BusinessServices.cuxwms)(this)).invokews(inValue);
            xReturnCode_out = retVal.xReturnCode_out;
            xReturnMesg_out = retVal.xReturnMesg_out;
            xResponseData_out = retVal.xResponseData_out;
        }
        
        public System.Threading.Tasks.Task<EWMS.WinService.BusinessServices.invokewsResponse> invokewsAsync(EWMS.WinService.BusinessServices.invokewsRequest request) {
            return base.Channel.invokewsAsync(request);
        }
    }
}
