--修改申领视图--
drop view V_JSLIST;
CREATE VIEW V_JSLIST AS 
SELECT
  A.ID,
  A.GUID,
  A.ERPID,
  A.ORDERID,
  A.ORDERNUM,
  A.BUSINESSID,
  A.ERPSTOCKORGID,
  A.STOCKORGID,
  A.STOCKORGCODE,
  A.ERPPROVIDERDEPID,
  A.PROVIDERDEPCODE,
  A.PROVIDERDEPNAME,
  A.PROVIDERPLACEID,
  A.PROVIDERPLACECODE,
  A.PROVIDERDEPID,
  A.ISSUEID,
  A.ISSUECODE,
  A.FYID,
  A.ERPROWNUM,
  A.ORDERROWID,
  A.MATERIALCODE,
  SUBSTR(A.MATERIALCODE,1,2) AS PARCODE,
  A.DESCRIPTION,
  A.DETAILUNIT,
  A.NOTAXPRICE,
  A.NOTAXSUM,
  A.BASEUNIT,
  A.BASEUNITCOUNT,
  A.BASEUNITPRICE,
  A.BASEUNITSUM,
  A.TAXRATE,
  A.CONSIGNMENT,
  A.DEPARTID,
  A.CREATOR,
  A.CREATEDATE,
  A.UPDATOR,
  A.UPDATEDATE,
  A.ORDERTYPE,
  B.NAME AS JSTYPE,
  C.ID AS MATERIALID, --物料id
  C.NAME AS MATERIALNAME,--物料名称
  C.SPECIFICATIONS as MATERIALSPECIFICATION,--物料规格
  C.MODEL AS MATERIALMODEL,--物料型号
  C.BRAND AS MATERIALBRAND,--物料品牌
  C.SPARESCATEID,--备件分类ID
     A.EXTENDSTRING1,
   A.EXTENDFLOAT2-(SELECT NVL( SUM(H.DETAILCOUNT),0)
  FROM  WZ_SHEETDETAIL H INNER JOIN WZ_SHEET I ON H.SHEETID=I.ID WHERE H.SHEETDETAILID=A.ID  and I.KINDID=588 and I.STATUS<>41) AS ISCOUNT

  FROM WZ_ORDERINFO A
  LEFT JOIN BASE_DICTIONARY B ON A.CONSIGNMENT=B.ID
  LEFT JOIN BASE_MATERIAL C ON A.MATERIALCODE=C.CODE 
  WHERE /*A.PURCHASETYPE=0 AND*/
  A.EXTENDFLOAT2>0
 AND  A.EXTENDFLOAT2>(SELECT NVL( SUM(H.DETAILCOUNT),0) 
  FROM  WZ_SHEETDETAIL H LEFT JOIN WZ_SHEET I ON H.SHEETID=I.ID WHERE H.SHEETDETAILID=A.ID  and I.KINDID=588 and I.STATUS<>41)
  AND A.EXTENDINT1>0;
  
  --修改入库视图--
drop view V_RKDETAILS;
CREATE VIEW V_RKDETAILS AS 
SELECT A.ID,
       A.GUID,
       A.SHEETID,
       A.SHEETDETAILID,
       A.CATEGORYID,
       A.MATERIALID,
       A.MATERIALCODE,
       A.MATERIALNAME,
       A.MATERIALBRAND,
       A.MATERIALMODEL,
       A.MATERIALSPECIFICATION,
       A.CREATOR,
       A.CREATEDATE,
       A.ZTID,
       A.NOTAXPRICE,
       A.TAXRATE,
       A.NOTAXSUM,
       A.DESCRIPTION,
       A.TAXPRICE,
       A.TAXSUM,
       A.ISEQUIPMENT,
       A.OWNERTYPE,
       A.ENABLESN,
       A.SNCODE,
       A.DETAILUNITNAME,
       A.EXTENDSTRING1,
       A.DETAILCOUNT,
       B.EXTENDSTRING1 AS PROVIDERNAME,
       (SELECT SUM(E.SUBDETAILCOUNT) FROM WZ_SHEETRKSUBDETAIL E WHERE E.DETAILID=A.ID) AS SUBTOTALCOUNT,
       C.NAME AS JSTYPE,
       A.EXTENDFLOAT1,
       (select wm_concat(to_char('[' || D.STORELOCATIONNAME) || ']') from wz_sheetrksubdetail D where D.detailid=A.Id) AS LOCATIONNAME,
       (SELECT NVL( SUM(Z.SUBDETAILCOUNT) ,0)AS Expr1 FROM WZ_SHEETRKSUBDETAIL Z WHERE (Z.DETAILID=A.ID)) AS SUMCOUNT,
       wh.id as storeID,
	   wh.name as warehouseName
   FROM WZ_SHEETRKDETAIL A
  LEFT JOIN WZ_SHEET_RK B ON A.SHEETID = B.ID
  LEFT JOIN BASE_DICTIONARY C ON A.OWNERTYPE=C.ID
  left join base_warehouse wh on A.EXTENDSTRING1=wh.code 
  WHERE B.KINDID=35;
  
 
--修改退库打印视图--
drop view V_TKD_PRINT;
CREATE VIEW V_TKD_PRINT AS 
SELECT
 A.ID,
 A.GUID,
 A.NAME,
 A.CODE,
 A.KINDID,
 A.TYPEID,
 A.DUTYID,
 A.DEPARTID,
 A.ROUTEID,
 A.ROUTE_STEPID,
 A.ROLEID,
 A.RELATESHEET,
 A.SUBMITMANID,
 A.SUBMITTIME,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.ZTID,
 A.ORDERNUM,
 A.RECEIVENUM,
 A.USEDDEPARTID,
 A.STOREMANID,
 A.USEDMANID,
 A.PROVIDERDEPID,
 A.OWNERDEP,
 A.FUNDSSOURCE,
 A.EXTENDSTRING1,
 A.EXTENDINT1,
 A.OFFICESID,
 B.NAME AS STATUSNAME,
 C.NAME AS PERSONNAME,
 --D.NAME AS USEDEPNAME,
 E.CODE TKCODE,
 F.NAME USEDEPNAME,
 G.NAME DEPARTOFFICENAME,
 H.NAME ZTIDNAME,
 I.CODE CKCODE,
 J.CODE AS HOUSECODE
 FROM WZ_SHEET A
 LEFT JOIN BASE_DICTIONARY B ON A.STATUS=B.ID
 LEFT JOIN BASE_PERSON C ON A.CREATOR=C.ID
 --LEFT JOIN BASE_ORGANIZATION D ON A.USEDDEPARTID=D.ID
 LEFT JOIN WZ_SHEET_CK E ON A.EXTENDINT1=E.ID
 LEFT JOIN BASE_USEDEP F ON A.USEDDEPARTID=F.ID
 LEFT JOIN BASE_USEDEP G ON A.OFFICESID=G.ID
 LEFT JOIN BASE_ORGANIZATION H ON A.ZTID=H.ID
 LEFT JOIN WZ_SHEET_CK I ON A.EXTENDINT1=I.ID
INNER JOIN BASE_WAREHOUSE J ON J.ID=(SELECT STOREID FROM WZ_SHEETDETAIL WHERE SHEETID=A.ID AND ROWNUM=1)
 WHERE A.KINDID=315;

 
--修改直接出库明细视图--
drop view V_CKLIST;
CREATE VIEW V_CKLIST AS 
 select distinct
 a.id,
 a.guid,
 a.sheetid,
 a.sheetdetailid,
 a.materialid,
 a.materialcode,
 a.materialname,
 a.materialbrand,
 a.materialmodel,
 a.detailunit,
 a.storeid,
 a.creator,
 a.createdate,
 a.ztid,
 a.materialspecification,
 a.description,
 a.tagcode,
 a.storelocationid,
 a.storelocationcode,
 --a.storelocationname,
 a.storecount,
 b.name as housename,
 c.name as unitname,
 a.categoryid,
 a.plandepartid,
 a.notaxprice,
 a.taxprice,
 a.taxrate,
 a.ordernum,
 b.name storelocationname,
 e.name storelocationareaname,
 d.name as planname,
 a.detailunitname,
 a.providerdepid,--供应商ID
 f.name providername,--供应商名称
 A.Storecount-( SELECT NVL(SUM(J.DETAILCOUNT),0)
 FROM WZ_SHEETCKDETAIL J LEFT JOIN Wz_Sheet_Ck K ON J.SHEETID=K.ID WHERE J.EXTENDINT2=A.ID
 --AND K.STATUS<>41
 ) AS UNSECOUNT,
 g.NAME OWNERTYPENAME,        --拥有方名称，例如寄售
  a.ownertype
 from wz_stock a
left join base_warehouse b on a.storeid=b.id
left join base_warehouse e on a.StoreLocationID=e.id
left join base_dictionary c on a.detailunit=c.id
left join base_organization d on a.plandepartid=d.id
LEFT JOIN BASE_DICTIONARY g ON a.ownertype=g.ID 
left join base_provider f on a.providerdepid=f.id

WHERE --A.PURCHASETYPE=0 and
A.Storecount-( SELECT NVL(SUM(J.DETAILCOUNT),0)
 FROM WZ_SHEETCKDETAIL J INNER JOIN Wz_Sheet_Ck K ON J.SHEETID=K.ID WHERE J.EXTENDINT2=A.ID
 --AND K.STATUS<>41
 ) <>0 and A.Storecount>0;
 
 
--修改采购计划查询视图--
drop view V_PURCHASEPLAN;
CREATE VIEW V_PURCHASEPLAN AS 
 SELECT p.ID,p.PLANCODE,p.CREATEDATE,
  case when to_char(p.NEEDDATE,'yyyymmdd')='00010101' Then null
    else p.NEEDDATE
  END as  NEEDDATE
  ,p.APPLYDEPID,p.USEDEPID,m.code as MATERIALCODE,p.MATERIALDES,p.PURCHASETYPE,p.PLANTYPE,p.SOURCETYPE,m.UNIT,p.COUNT,p.PRICE,p.BASEUNIT,p.BASECOUNT,p.BASEPRICE,p.PURCHASEMODEL,p.MANUFACTURER,p.UPDATEDATE,p.ERPID,p.ORDERTYPE,p.CONSIGNMENT,p.ZTID,p.EXTENDINT1,p.EXTENDINT2,p.EXTENDINT3,p.EXTENDINT4,p.EXTENDINT5,p.EXTENDINT6,p.EXTENDFLOAT1,p.EXTENDFLOAT2,p.EXTENDFLOAT3,p.EXTENDFLOAT4,p.EXTENDFLOAT5,p.EXTENDFLOAT6,p.EXTENDSTRING1,p.EXTENDSTRING2,p.EXTENDSTRING3,p.EXTENDSTRING4,p.EXTENDSTRING5,p.EXTENDSTRING6,p.EXTENDSTRING7,p.EXTENDSTRING8,
  u.name as USEDEPNAME, a.name as APPLYDEPNAME ,
  p.erpdetailid, case when  p.ExtendInt1=1 then '正常' else '取消' END as status

from WZ_PURCHASEPLAN p
LEFT OUTER join base_usedep u on p.usedepid=u.id
LEFT OUTER join base_organization a on p.applydepid= a.id
LEFT OUTER join base_material m on m.code=p.MATERIALCODE;
 
 
 --修改采购订单视图--
drop view V_ORDERINFO;
CREATE VIEW V_ORDERINFO AS 
SELECT
   A.id AS ID,
   A.erpid AS erpid,
   A.ORDERNUM,
   A.PROVIDERDEPNAME,
   A.STOCKORGID,
   A.ORDERTYPE,
   A.ISSUECODE,
   B.NAME
 AS STOCKORGNAME,
   A.providerdepid,
   A.Fyid,
   A.Orderid,
   A.Issueid,
   A.Erprownum,
   A.Orderrowid,
--   SUM(A.DETAILCOUNT) AS ALLCOUNT,
   nvl(nvl(SUM(A.EXTENDFLOAT2),0)- nvl((SELECT SUM(detail.DETAILCOUNT) FROM wz_sheetdetail detail left join WZ_SHEET sheet on detail.sheetid=sheet.id
   left  join WZ_ORDERINFO info on detail.sheetdetailid=info.id 
   where info.erpid=a.erpid 
   and sheet.KINDID=588 and sheet.STATUS<>41 ),0),0) AS CANUSEDCOUNT
  FROM WZ_ORDERINFO A LEFT JOIN BASE_ORGANIZATION B ON A.STOCKORGID=B.ID
  WHERE A.EXTENDINT1>0 and (exists(
        select 1 from v_jslist vj 
        where  vj.ISCOUNT > 0 and  vj.ORDERNUM = A.ORDERNUM ) 
        or A.ORDERNUM not in (select j.ORDERNUM from v_jslist j)
        )
  GROUP BY A.id,A.erpid,A.ORDERNUM,A.PROVIDERDEPNAME,A.STOCKORGID,A.ORDERTYPE,B.NAME, A.ISSUECODE,A.providerdepid,
  A.Fyid, A.ORDERID,A.ISSUEID,A.ERPROWNUM,A.ORDERROWID;
 
--修改库位标签打印视图--
drop view V_LOCATION;
CREATE VIEW V_LOCATION AS 
 SELECT 
 distinct case
            when instr(A.CODE,'S')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'J')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'C')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'ZM')=1 then  SUBSTR(A.CODE,3)
            when instr(A.CODE,'ZH')=1 then  SUBSTR(A.CODE,3)
            when instr(A.CODE,'(')>1 then  SUBSTR(A.CODE,1,instr(A.CODE,'(')-1)
            when instr(A.CODE,'（')>1 then  SUBSTR(A.CODE,1,instr(A.CODE,'(')-1)
            else A.CODE end
       as CODE,
         case
            when instr(A.CODE,'S')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'J')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'C')=1 then  SUBSTR(A.CODE,2)
            when instr(A.CODE,'ZM')=1 then  SUBSTR(A.CODE,3)
            when instr(A.CODE,'ZH')=1 then  SUBSTR(A.CODE,3)
            when instr(A.CODE,'(')>1 then  SUBSTR(A.CODE,1,instr(A.CODE,'(')-1)
            when instr(A.CODE,'（')>1 then  SUBSTR(A.CODE,1,instr(A.CODE,'(')-1)
            else A.CODE end
       as sheetid,
       a.id,
       a.name,
       c.name as parent_name,
       --A.CODE,
       A.ZTID,
       B.NAME  ZTIDNAME
FROM BASE_WAREHOUSE A 
LEFT JOIN BASE_ORGANIZATION B
ON A.ZTID=B.ID
LEFT JOIN BASE_WAREHOUSE C 
ON A.parentId=C.id
WHERE A.PARENTID!=0 and A.Status=1 and A.code is not null;

--修改库存查询视图--
drop view V_KCDETAIL;
CREATE VIEW V_KCDETAIL AS 
select t."MATERIALCODE",t."MATERIALNAME",t."MATERIALBRAND",t."MATERIALMODEL",t."MATERIALSPECIFICATION",t."STOREID",t."DESCRIPTION",t."ZTID",t."OWNERTYPE",t."OWNERTYPENAME",t."PROVIDERDEPID",t."PROVIDERNAME",t."ZTIDNAME",t."STORECOUNT",t."HOUSENAME",t."FLNAME",
t."STORELOCATIONCODE",t."STORELOCATIONNAME",rownum as id from (
SELECT 
 distinct  stock.MATERIALCODE,              --物料编码
stock.MATERIALNAME,              --物料名称
stock.MATERIALBRAND,             --物料品牌
stock.MATERIALMODEL,             --物料型号
stock.MATERIALSPECIFICATION,     --物料规格
stock.STOREID,                   --库房ID
stock.DESCRIPTION,               --物料说明
stock.ZTID,                      --库存组织
stock.OWNERTYPE,                 --拥有方类型
E.NAME OWNERTYPENAME,        --拥有方名称，例如寄售
stock.PROVIDERDEPID,             --供应商ID
stock.STORELOCATIONCODE,             --库位编码
stock.STORELOCATIONNAME,                 --库位名称
F.NAME

 PROVIDERNAME,         --供应商名称
G.NAME

 ZTIDNAME,              --组织机构
(select  sum(wz_stock.storecount) from wz_stock where wz_stock.materialcode=stock.materialcode and wz_stock.storeid=stock.storeid and wz_stock.STORELOCATIONCODE =  stock.STORELOCATIONCODE ) as STORECOUNT,--库存数量
B.NAME AS HOUSENAME,         --库房名称
D.NAME  AS FLNAME        --物料分类名称 

FROM wz_stock stock 
INNER JOIN (select a.materialid,ztid,storeid, ownertype, providerdepid  
from wz_stock a  group by a.materialid,ztid,storeid, ownertype, providerdepid ) C 
ON stock.materialid=C.materialid and stock.ztid=C.ztid and stock.storeid=C.storeid and stock.ownertype=C.ownertype and stock.providerdepid=C.providerdepid
LEFT JOIN BASE_WAREHOUSE B  ON stock.STOREID=B.ID
LEFT JOIN BASE_SPAREPARTSCATE D ON substr(stock.MaterialCode,0,2)=D.code 
LEFT JOIN BASE_DICTIONARY E ON stock.OWNERTYPE=E.ID
LEFT JOIN BASE_PROVIDER F ON stock.PROVIDERDEPID=F.ID
LEFT JOIN BASE_ORGANIZATION G ON stock.ZTID=G.ID
)t;

--修改入库查询视图--
drop view V_RKCX;
CREATE VIEW V_RKCX AS 
SELECT
 to_char(A.ID+dbms_random.value(0,10)) as id,
 A.GUID,
 A.TAGCODE,
 A.SHEETID,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 B.SUBDETAILCOUNT,
 A.DETAILUNIT,
 B.STOREID,
 B.STORELOCATIONID,
 B.STORELOCATIONCODE,
 B.STORELOCATIONNAME,
 A.NOTAXPRICE,
 A.TAXRATE,
 A.NOTAXSUM,
 A.TAXPRICE,
 A.TAXSUM,
 C.CODE,
 C.ROUTEID,
 C.ROUTE_STEPID,
 C.STATUS AS SHEETSTATUS ,
 C.SUBMITTIME,
  (CASE C.KINDID
    WHEN 35     THEN '正常入库'
    WHEN 832     THEN '杂入入库'
    ELSE '其他' END) AS KINDNAME,
 D.NAME AS HOUSENAME,
 C.ZTID,
 c.url
 FROM WZ_SHEETRKDETAIL A 
 LEFT JOIN WZ_SHEETRKSUBDETAIL B ON A.ID=B.DETAILID
 LEFT JOIN WZ_SHEET_RK C ON A.SHEETID=C.ID
 LEFT JOIN BASE_WAREHOUSE D ON B.STOREID=D.ID WHERE C.STATUS=41 AND C.KINDID in (35,832);
 
 --修改出库查询视图--
drop view V_CKCX;
CREATE VIEW V_CKCX AS 
SELECT
 A.ID,
 A.GUID,
 A.TAGCODE,
 A.SHEETID,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 A.DETAILCOUNT,
 A.DETAILUNIT,
 A.STOREID,
 A.STORELOCATIONID,
 A.STORELOCATIONNAME,
 A.STORELOCATIONCODE,
 B.CODE,
 B.USEDDEPARTID,
 C.NAME AS USDEDEPNAME,
 '正常出库' AS KINDNAME,
 B.ZTID,
 B.Url
 FROM WZ_SHEETCKDETAIL A LEFT JOIN WZ_SHEET_CK B ON A.SHEETID=B.ID
 LEFT JOIN BASE_USEDEP C ON B.USEDDEPARTID=C.ID WHERE B.STATUS=41
 union
 SELECT
 A.ID,
 A.GUID,
 A.TAGCODE,
 A.SHEETID,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 A.DETAILCOUNT,
 A.DETAILUNIT,
 A.STOREID,
 A.STORELOCATIONID,
 A.STORELOCATIONNAME,
 A.STORELOCATIONCODE,
 B.CODE,
 B.USEDDEPARTID,
 C.NAME AS USDEDEPNAME,
 '杂出出库' AS KINDNAME,
 B.ZTID,
 B.Url
 FROM WZ_SHEETDETAIL A LEFT JOIN WZ_SHEET B ON A.SHEETID=B.ID
 LEFT JOIN BASE_USEDEP C ON B.USEDDEPARTID=C.ID WHERE B.STATUS=41 and B.KINDID=835;
 
 --修改上下线告警查询视图--
drop view V_SXX;
CREATE VIEW V_SXX AS 
select bm."ID",bm."GUID",bm."NAME",bm."MODEL",bm."BRAND",bm."SPARESCATEID",bm."PRICE",bm."STATUS",bm."CONFIGMEMO",bm."PROVIDERID",bm."MEMO",bm."SORT",bm."CREATOR",bm."CREATEDATE",bm."UPDATER",bm."UPDATEDATE",bm."ZTID",bm."EXTENDINT1",bm."EXTENDINT2",bm."EXTENDINT3",bm."EXTENDINT4",bm."EXTENDFLOAT1",bm."EXTENDFLOAT2",bm."EXTENDFLOAT3",bm."EXTENDFLOAT4",bm."EXTENDSTRING1",bm."EXTENDSTRING2",bm."EXTENDSTRING3",bm."EXTENDSTRING4",bm."EXTENDSTRING5",bm."CODE",bm."SPECIFICATIONS",bm."MODELS",bm."UNIT",bm."STOCKUP",bm."STOCKDOWN",bm."ISUSEALARM",bm."DESCRIPTION",nvl(wz.storecount,0) as con from base_material bm
 left join wz_stock wz on bm.id=wz.materialid
WHERE IsUseAlarm = 1 and  (nvl(wz.storecount,0)<bm.stockdown
 or ( nvl(wz.storecount,0)> bm.StockUp));

 
--修改打印退货视图--
drop view V_THD_Print;
CREATE VIEW V_THD_Print AS 
 SELECT
 A.ID,
 A.GUID,
 A.NAME,
 A.CODE,
 A.KINDID,
 A.TYPEID,
 A.DUTYID,
 A.DEPARTID,
 A.ROUTEID,
 A.ROUTE_STEPID,
 A.ROLEID,
 A.RELATESHEET,
 A.SUBMITMANID,
 A.SUBMITTIME,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.ZTID,
 A.ORDERNUM,
 A.RECEIVENUM,
/* A.USEDDEPARTID,*/
 A.STOREMANID,
 A.USEDMANID,
 A.PROVIDERDEPID,
 A.OWNERDEP,
 A.EXTENDSTRING1,--供应商
 A.EXTENDSTRING2,--库存组织
 A.EXTENDSTRING3,--订单类型
 A.EXTENDSTRING4,--业务实体
 A.EXTENDSTRING5,--入库单号
 A.EXTENDSTRING6,--接收号
 A.EXTENDINT1,
 B.NAME AS STATUSNAME,
 C.NAME AS PERSONNAME,
 D.NAME AS PROVIDERNAME,
 E.NAME AS DEPNAME,
 F.CODE AS HOUSECODE,
 A.EXTENDSTRING7, --ERP接收单号
 G.RECEIVENUM AS JSCODE,
 A.url
 FROM WZ_SHEET A LEFT JOIN BASE_DICTIONARY B ON A.STATUS=B.ID
 LEFT JOIN BASE_PERSON C ON A.CREATOR=C.ID
 LEFT JOIN BASE_PROVIDER D ON A.PROVIDERDEPID=D.ID
 LEFT JOIN BASE_ORGANIZATION E ON A.DEPARTID=E.ID
 INNER JOIN BASE_WAREHOUSE F ON F.ID=(SELECT STOREID FROM WZ_SHEETDETAIL WHERE sheetid=A.ID AND ROWNUM=1)
 LEFT JOIN WZ_SHEET_RK G ON A.EXTENDSTRING5=G.code
 WHERE A.KINDID=485;

--修改打印退货明细视图--
drop view V_THDETAILS;
CREATE VIEW V_THDETAILS AS 
SELECT
 C.NAME AS HOUSENAME,
 A.ID,
 A.GUID,
 A.SHEETID,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.DETAILCOUNT,
 A.DETAILUNIT,
 A.CURRENCYUNIT,
 A.STOREID,
 A.PROVIDERDEPID,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.UPDATOR,
 A.UPDATEDATE,
 A.ZTID,
 A.NOTAXPRICE,
 A.TAXRATE,
 A.NOTAXSUM,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 A.EXPIRATIONTIME,
 A.STORELOCATIONCODE,
 A.TAGCODE,
 A.TAXPRICE,
 A.TAXSUM,
 A.STORELOCATIONID,
 A.PLANDEPARTID,
 A.DETAILUNITNAME,
 A.ISEQUIPMENT,
 A.ENABLESN,
 A.SNCODE,
 A.EXTENDFLOAT1,
 G.name AS STORELOCATIONNAME,
 E.NAME AS FLNAME,
 F.CODE AS JSCODE,
 JS.GUID AS JSGUID,
 H.SPECIFICATIONS AS SPECIFICATIONS,
 A.extendString10 AS ERPROWNUM,
 A.Extendint8
FROM WZ_SHEETDETAIL A
LEFT JOIN WZ_SHEETRKSUBDETAIL  B ON A.EXTENDINT8=B.ID
LEFT JOIN WZ_SHEETRKDETAIL BB ON B.DETAILID=BB.ID
LEFT JOIN WZ_SHEETDETAIL JS ON BB.SHEETDETAILID=JS.ID
LEFT JOIN BASE_WAREHOUSE C ON A.STOREID=C.ID
LEFT JOIN WZ_SHEET D ON A.SHEETID=D.ID
LEFT JOIN BASE_SPAREPARTSCATE E ON A.CATEGORYID=E.ID
LEFT JOIN BASE_DICTIONARY F ON A.OWNERTYPE=F.ID
LEFT JOIN BASE_WAREHOUSE G ON A.STORELOCATIONID=G.ID
LEFT JOIN BASE_MATERIAL H ON A.MATERIALCODE=H.code
WHERE D.KINDID=485;
--修改接收明细视图--
drop view V_JSD;
CREATE VIEW V_JSD AS 
SELECT
  A.ID,
  A.GUID,
  A.NAME,
  A.CODE,
  A.KINDID,
  A.TYPEID,
  A.DUTYID,
  A.DEPARTID,
  A.ROUTEID,
  A.ROUTE_STEPID,
  A.ROLEID,
  A.RELATESHEET,
  A.SUBMITMANID,
  A.SUBMITTIME,
  A.STATUS,
  A.MEMO,
  A.CREATOR,
  A.CREATEDATE ,
  A.UPDATOR,
  A.UPDATEDATE,
  A.ZTID,
  A.EXTENDSTRING1,
  A.EXTENDSTRING2,
  A.EXTENDSTRING3,
  A.EXTENDSTRING4,
  A.EXTENDSTRING5,
  A.EXTENDSTRING10,
  A.ORDERNUM,
  B.NAME AS PERSONNAME,
  C.NAME AS STATUSNAME,
  A.PROVIDERDEPID,
  D.NAME AS DEPNAME,
  A.EXTENDINT1,
  A.URL
  FROM WZ_SHEET A LEFT JOIN BASE_PERSON B
  ON A.CREATOR=B.ID
  LEFT JOIN BASE_DICTIONARY C
  ON A.STATUS=C.ID
  LEFT JOIN BASE_ORGANIZATION D
  ON A.DEPARTID=D.ID;
  
--修改接收入库明细视图--
drop view V_JSRKLIST;
CREATE VIEW V_JSRKLIST AS 
SELECT
 A.ID,
 A.GUID,
 A.SHEETID,
 B.CODE AS JSCODE,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.PROVIDERDEPID,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.ZTID,
 A.NOTAXPRICE,
 A.TAXRATE,
 A.NOTAXSUM,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 A.TAXPRICE,
 A.TAXSUM,
 A.DETAILCOUNT,
 A.ISEQUIPMENT,
 A.ENABLESN,
 A.SNCODE,
 A.OWNERTYPE,
 A.DETAILUNITNAME,
 A.EXTENDDATE2,
 D.NAME AS PLANDEPNAME,
 A.EXPIRATIONTIME,
 A.PLANDEPARTID,
 C.NAME AS JSTYPE,
 C.CODE AS JSTYPECODE,
 A.EXTENDSTRING1,
 A.EXTENDSTRING10 as erpRowNum,
 B.EXTENDSTRING1 AS PROVIDERNAME,
 A.DETAILCOUNT-NVL((SELECT sum(L.COUNT) FROM WZ_RECEIVINGLOG L WHERE L.RELATIONGUID=A.GUID AND L.OPERATIONTYPE=2),0) AS JSCOUNT,
 NVL((SELECT sum(STORECOUNT) FROM WZ_STOCK K LEFT JOIN WZ_SHEETRKDETAIL R ON K.SHEETDETAILID=R.ID WHERE R.SHEETDETAILID=A.ID),0) AS KCOUNT,
 (SELECT NVL( SUM(H.DETAILCOUNT),0)FROM  WZ_SHEETRKDETAIL H INNER JOIN WZ_SHEET_RK I ON H.SHEETID=I.ID WHERE H.SHEETDETAILID=A.ID/* AND I.STATUS<>41*/) AS ISCOUNT,
A.ExtendInt1

 FROM WZ_SHEETDETAIL A LEFT JOIN WZ_SHEET B ON A.SHEETID=B.ID
 LEFT JOIN BASE_DICTIONARY C ON A.OWNERTYPE=C.ID
 LEFT JOIN BASE_ORGANIZATION D ON A.PLANDEPARTID = D.ID
 WHERE B.KINDID=588;
 
 
  
--修改退货明细视图--
drop view V_THLIST;
CREATE VIEW V_THLIST AS 
SELECT
 rownum realId,
 A.ID,
 A.GUID,
 A.SHEETID,
 A.SHEETDETAILID,
 A.CATEGORYID,
 A.MATERIALID,
 A.MATERIALCODE,
 A.MATERIALNAME,
 A.MATERIALBRAND,
 A.MATERIALMODEL,
 A.DETAILUNIT,
 A.PROVIDERDEPID,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.ZTID,
 A.NOTAXPRICE,
 A.TAXRATE,
 A.NOTAXSUM,
 A.MATERIALSPECIFICATION,
 A.DESCRIPTION,
 A.EXPIRATIONTIME,
 A.TAXPRICE,
 A.TAXSUM,
 A.PLANDEPARTID,
 A.DETAILCOUNT,
 A.ISEQUIPMENT,
 A.OWNERTYPE,
 A.ENABLESN,
 C.SNCODE,
 A.DETAILUNITNAME,
 A.EXTENDSTRING1,--库房编码
 A.EXTENDFLOAT1,
 C.STOREID,
 C.SUBDETAILCOUNT,
 A.EXTENDSTRING10 as erpRowNum,
 B.CODE AS SHEETCODE,
 B.ORDERNUM,
 C.ID AS SONID,
 nvl(f_GetStockUseCount(a.materialcode,a.ztid),0) AS STOREUSEDCOUNT,
 --已退货数量
 (SELECT NVL(SUM(THList.DETAILCOUNT),0) FROM WZ_SHEETDETAIL THList LEFT JOIN WZ_SHEET TH ON THList.SHEETID=TH.ID WHERE  THList.Extendint8=C.ID AND TH.KINDID=485 ) AS YTCOUNT
 FROM WZ_SHEETRKDETAIL A LEFT JOIN WZ_SHEET_RK B ON A.SHEETID=B.ID LEFT JOIN WZ_SHEETRKSUBDETAIL C ON A.ID=C.DETAILID
 WHERE B.KINDID=35;
 

--修改可退库的出库单视图--
drop view V_CKNUM;
CREATE VIEW V_CKNUM AS 
 select distinct a.id,
       a.code ckSheetCode,
       a.useddepartid,
       b.name useddepartname,
       a.officesid,
       d.name officesname,
       a.fundssource,
       c.name fundssourcename,
       a.extendstring1,--用途
       a.extendint3,
       a.createdate,
       llsheet.code as llSheetCode
from wz_sheet_ck a
inner join wz_sheetckdetail e on a.id= e.sheetid
left join base_usedep b on a.useddepartid=b.id
left join base_dictionary c on a.fundssource=c.id
left join base_usedep d on a.officesid=d.id
left join wz_sheetdetail lldetail on e.sheetdetailid=lldetail.id
left join wz_sheet llsheet on lldetail.sheetid=llsheet.id
where a.status=41 and a.extendint3 = 1
 and  e.detailcount> (select nvl(sum(TKdetail.Detailcount),0) from wz_sheetdetail TKdetail   --如果出库单中的物资已经全部退库就不在显示
            left join wz_sheet TKsheet on TKdetail.sheetid=TKsheet.id
            where TKdetail.Sheetdetailid=e.id);
					

--修改退库单打印视图--
drop view V_TKD_PRINT;
CREATE VIEW V_TKD_PRINT AS 					
SELECT
 A.ID,
 A.GUID,
 A.NAME,
 A.CODE,
 A.KINDID,
 A.TYPEID,
 A.DUTYID,
 A.DEPARTID,
 A.ROUTEID,
 A.ROUTE_STEPID,
 A.ROLEID,
 A.RELATESHEET,
 A.SUBMITMANID,
 A.SUBMITTIME,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.ZTID,
 A.ORDERNUM,
 A.RECEIVENUM,
 A.USEDDEPARTID,
 A.STOREMANID,
 A.USEDMANID,
 A.PROVIDERDEPID,
 A.OWNERDEP,
 A.FUNDSSOURCE,
 A.EXTENDSTRING1,
 A.EXTENDINT1,
 A.OFFICESID,
 B.NAME AS STATUSNAME,
 C.NAME AS PERSONNAME,
 --D.NAME AS USEDEPNAME,
 E.CODE TKCODE,
 F.NAME USEDEPNAME,
 G.NAME DEPARTOFFICENAME,
 H.NAME ZTIDNAME,
 E.CODE CKCODE,
 I.name AS APPLYDEPNAME,
 J.CODE AS HOUSECODE
 FROM WZ_SHEET A
 LEFT JOIN BASE_DICTIONARY B ON A.STATUS=B.ID
 LEFT JOIN BASE_PERSON C ON A.CREATOR=C.ID
 --LEFT JOIN BASE_ORGANIZATION D ON A.USEDDEPARTID=D.ID
 LEFT JOIN WZ_SHEET_CK E ON A.EXTENDINT1=E.ID
 LEFT JOIN BASE_USEDEP F ON A.USEDDEPARTID=F.ID
 LEFT JOIN BASE_USEDEP G ON A.OFFICESID=G.ID
 LEFT JOIN BASE_ORGANIZATION H ON A.ZTID=H.ID
 LEFT JOIN BASE_APPLYDEP I ON E.applydepartid=I.id
INNER JOIN BASE_WAREHOUSE J ON J.ID=(SELECT STOREID FROM WZ_SHEETDETAIL WHERE SHEETID=A.ID AND ROWNUM=1)
 WHERE A.KINDID=315;
 
 --修改退库单视图--
drop view V_TKD;
CREATE VIEW V_TKD AS 		
 SELECT
 A.ID,
 A.GUID,
 A.NAME,
 A.CODE,
 A.KINDID,
 A.TYPEID,
 A.DUTYID,
 A.DEPARTID,
 A.ROUTEID,
 A.ROUTE_STEPID,
 A.ROLEID,
 A.RELATESHEET,
 A.SUBMITMANID,
 A.SUBMITTIME,
 A.STATUS,
 A.MEMO,
 A.CREATOR,
 A.CREATEDATE,
 A.UPDATOR,
 A.UPDATEDATE,
 A.ZTID,
 A.ORDERNUM,
 A.RECEIVENUM,
 A.USEDDEPARTID,
 A.STOREMANID,
 A.USEDMANID,
 A.PROVIDERDEPID,
 A.OWNERDEP,
 A.FUNDSSOURCE,
 A.EXTENDSTRING1,
 A.EXTENDINT1,
 A.EXTENDINT3,
 A.OFFICESID,
 B.NAME AS STATUSNAME,
 C.NAME AS PERSONNAME,
 --D.NAME AS USEDEPNAME,
 E.CODE TKCODE,
 F.NAME USEDEPNAME,
 G.NAME DEPARTOFFICENAME,
 H.NAME ZTIDNAME,
 I.CODE CKCODE，
 A.url
/*， J.CODE AS HOUSECODE*/
 FROM WZ_SHEET A
 LEFT JOIN BASE_DICTIONARY B ON A.STATUS=B.ID
 LEFT JOIN BASE_PERSON C ON A.CREATOR=C.ID
 --LEFT JOIN BASE_ORGANIZATION D ON A.USEDDEPARTID=D.ID
 LEFT JOIN WZ_SHEET_CK E ON A.EXTENDINT1=E.ID
 LEFT JOIN BASE_USEDEP F ON A.USEDDEPARTID=F.ID
 LEFT JOIN BASE_USEDEP G ON A.OFFICESID=G.ID
 LEFT JOIN BASE_ORGANIZATION H ON A.ZTID=H.ID
 LEFT JOIN WZ_SHEET_CK I ON A.EXTENDINT1=I.ID
/*INNER JOIN BASE_WAREHOUSE J ON J.ID=(SELECT STOREID FROM WZ_SHEETDETAIL WHERE SHEETID=A.ID AND ROWNUM=1)*/
 WHERE A.KINDID=315;