package com.zthc.ewms.webservice.axis2;

import java.rmi.RemoteException;

public class test {
    public static void main(String[] a) {
        //ESB headers
//         esbPortProxy = new ESBPortProxy();
        CuxwmsStub stub = ESBPortProxy.getPayEntity();
        if (stub == null || "".equals(stub)) {
            return;
        }
        //±¨ÎÄ
        CuxwmsStub.Invokews invokews = new CuxwmsStub.Invokews();
        invokews.setPIfaceCode("CUXYXPOREC");
        invokews.setPBatchNumber("10000");
        invokews.setPRequestData("PFdTSU5URVJGQUNFPgo8UkVDX0lORk8+CjxIRUFERVJfSUQ+MTwvSEVBREVSX0lEPgo8RE9DX05VTT4xPC9ET0NfTlVNPgo8T1JHQU5JWkFUSU9OX0lEPjMyODwvT1JHQU5JWkFUSU9OX0lEPgo8VkVORE9SX0lEPjE1MDM3MDU8L1ZFTkRPUl9JRD4KPFZFTkRPUl9OVU1CRVI+MjAwMjAxNjQ8L1ZFTkRPUl9OVU1CRVI+CjxWRU5ET1JfTkFNRT7lroHms6LogZrlipvntKflm7rku7bmnInpmZDlhazlj7g8L1ZFTkRPUl9OQU1FPgo8REVQVF9JRD4xPC9ERVBUX0lEPgo8TUFLRVJfSUQ+MTwvTUFLRVJfSUQ+CjxNQUtFUl9OQU1FPjE8L01BS0VSX05BTUU+CjxNQUtFUl9EQVRFPjIwMTctMDItMjA8L01BS0VSX0RBVEU+CjxVUERBVEVfQllfSUQ+MTwvVVBEQVRFX0JZX0lEPgo8VVBEQVRFX0RBVEU+MjAxNy0wMi0yMDwvVVBEQVRFX0RBVEU+CjxPUkdfSUQ+Mjg5NzwvT1JHX0lEPgo8UkVDRUlQVF9EQVRFPjIwMTctMDEtMjA8L1JFQ0VJUFRfREFURT4KPEJBVENIX05BTUU+MjAxNzAyMjAwMDAwMDA8L0JBVENIX05BTUU+CjxQUk9DRVNTX1RZUEU+T05MSU5FPC9QUk9DRVNTX1RZUEU+CjxSRUNfTElORV9JTkZPPgo8TElORV9JRD4xPC9MSU5FX0lEPgo8VU9NPuadoTwvVU9NPgo8UVVBTlRJVFk+MjwvUVVBTlRJVFk+CjxJVEVNX05PPjEwMDMwMTEwNjc0MTwvSVRFTV9OTz4KPElURU1fREVTQz7ohqjog4DonrrmoJN8TTEybW3DlzExMG1tUTIzNTwvSVRFTV9ERVNDPgo8U1VCSU5WX0NPREU+QzAwMTwvU1VCSU5WX0NPREU+CjxMT0NBVE9SX0lEPjQwOTEyMjwvTE9DQVRPUl9JRD4KPExPQ0FUT1JfQ09ERT4wNC0zMi0wMS0wMjwvTE9DQVRPUl9DT0RFPgo8QVNTRVRfTlVNQkVSPjwvQVNTRVRfTlVNQkVSPgo8VU5JVF9QUklDRT4xPC9VTklUX1BSSUNFPgo8QU1PVU5UPjE8L0FNT1VOVD4KPEJBU0VfVU5JVF9QUklDRT4xPC9CQVNFX1VOSVRfUFJJQ0U+CjxCQVNFX0FNT1VOVD4xPC9CQVNFX0FNT1VOVD4KPFBPX0xJTkVfTE9DQVRJT05fSUQ+NDE1NTc1NzwvUE9fTElORV9MT0NBVElPTl9JRD4KPFBPX05VTUJFUj5aVE1ULTIwMTYtMDItMDI3NV8wMTwvUE9fTlVNQkVSPgo8UE9fSEVBREVSX0lEPjE0MDg4MDA8L1BPX0hFQURFUl9JRD4KPFBPX0xJTkVfTlVNPjE8L1BPX0xJTkVfTlVNPgo8UE9fTElORV9JRD40Mjc3OTMzPC9QT19MSU5FX0lEPgo8UE9fUkVMRUFTRV9OVU0+PC9QT19SRUxFQVNFX05VTT4KPFBPX1JFTEVBU0VfSUQ+PC9QT19SRUxFQVNFX0lEPgo8L1JFQ19MSU5FX0lORk8+CjwvUkVDX0lORk8+CjwvV1NJTlRFUkZBQ0U+");
        invokews.setXReturnCode_out("?");
        invokews.setXReturnMesg_out("?");
        invokews.setXResponseData_out("?");
        try {
            //ÇëÇó
            CuxwmsStub.InvokewsResponse response = stub.invokews(invokews);
            System.out.println(response.getXResponseData_out());
        } catch (RemoteException e) {
            e.printStackTrace();
        }


    }
}
