//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWMS.WinService.VendorServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PovendorsRPoVendoresRecUserArray", Namespace="http://com/oracle/apps/povendors/POVENDORS.wsdl/types/", ItemName="PovendorsRPoVendoresRecUser")]
    [System.SerializableAttribute()]
    public class PovendorsRPoVendoresRecUserArray : System.Collections.Generic.List<EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUser> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PovendorsRPoVendoresRecUser", Namespace="http://com/oracle/apps/povendors/POVENDORS.wsdl/types/")]
    [System.SerializableAttribute()]
    public partial class PovendorsRPoVendoresRecUser : EWMS.WinService.VendorServices.PovendorsRPoVendoresRecBase {
        
        private string orgTypeField;
        
        private string vendorNameAltField;
        
        private System.Nullable<System.DateTime> siteLastUpdateDateField;
        
        private string attribute15Field;
        
        private System.Nullable<System.DateTime> siteCreationDateField;
        
        private string vendorNumberField;
        
        private string num1099Field;
        
        private string vendorSiteCodeField;
        
        private string vendorTypeLookupCodeField;
        
        private string cityField;
        
        private System.Nullable<decimal> orgIdField;
        
        private string createdByNameField;
        
        private string lastUpdatedByNameField;
        
        private string zipField;
        
        private System.Nullable<decimal> vendorSiteIdField;
        
        private string vendorNameField;
        
        private string vatRegistrationNumField;
        
        private string attributeCategoryField;
        
        private System.Nullable<decimal> vendorIdField;
        
        private string addressLine1Field;
        
        private string countryField;
        
        private System.Nullable<System.DateTime> lastUpdateDateField;
        
        private string attribute4Field;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string attribute5Field;
        
        private System.Nullable<System.DateTime> endDateActiveField;
        
        private string attribute6Field;
        
        private string attribute7Field;
        
        private string attribute8Field;
        
        private string employeeNumField;
        
        private string attribute9Field;
        
        private string attribute10Field;
        
        private string attribute11Field;
        
        private string attribute1Field;
        
        private string attribute12Field;
        
        private string attribute2Field;
        
        private string attribute13Field;
        
        private string attribute3Field;
        
        private string attribute14Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string orgType {
            get {
                return this.orgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.orgTypeField, value) != true)) {
                    this.orgTypeField = value;
                    this.RaisePropertyChanged("orgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string vendorNameAlt {
            get {
                return this.vendorNameAltField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorNameAltField, value) != true)) {
                    this.vendorNameAltField = value;
                    this.RaisePropertyChanged("vendorNameAlt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> siteLastUpdateDate {
            get {
                return this.siteLastUpdateDateField;
            }
            set {
                if ((this.siteLastUpdateDateField.Equals(value) != true)) {
                    this.siteLastUpdateDateField = value;
                    this.RaisePropertyChanged("siteLastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string attribute15 {
            get {
                return this.attribute15Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute15Field, value) != true)) {
                    this.attribute15Field = value;
                    this.RaisePropertyChanged("attribute15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> siteCreationDate {
            get {
                return this.siteCreationDateField;
            }
            set {
                if ((this.siteCreationDateField.Equals(value) != true)) {
                    this.siteCreationDateField = value;
                    this.RaisePropertyChanged("siteCreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string vendorNumber {
            get {
                return this.vendorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorNumberField, value) != true)) {
                    this.vendorNumberField = value;
                    this.RaisePropertyChanged("vendorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string num1099 {
            get {
                return this.num1099Field;
            }
            set {
                if ((object.ReferenceEquals(this.num1099Field, value) != true)) {
                    this.num1099Field = value;
                    this.RaisePropertyChanged("num1099");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string vendorSiteCode {
            get {
                return this.vendorSiteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorSiteCodeField, value) != true)) {
                    this.vendorSiteCodeField = value;
                    this.RaisePropertyChanged("vendorSiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string vendorTypeLookupCode {
            get {
                return this.vendorTypeLookupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorTypeLookupCodeField, value) != true)) {
                    this.vendorTypeLookupCodeField = value;
                    this.RaisePropertyChanged("vendorTypeLookupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> orgId {
            get {
                return this.orgIdField;
            }
            set {
                if ((this.orgIdField.Equals(value) != true)) {
                    this.orgIdField = value;
                    this.RaisePropertyChanged("orgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string createdByName {
            get {
                return this.createdByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.createdByNameField, value) != true)) {
                    this.createdByNameField = value;
                    this.RaisePropertyChanged("createdByName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string lastUpdatedByName {
            get {
                return this.lastUpdatedByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastUpdatedByNameField, value) != true)) {
                    this.lastUpdatedByNameField = value;
                    this.RaisePropertyChanged("lastUpdatedByName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<decimal> vendorSiteId {
            get {
                return this.vendorSiteIdField;
            }
            set {
                if ((this.vendorSiteIdField.Equals(value) != true)) {
                    this.vendorSiteIdField = value;
                    this.RaisePropertyChanged("vendorSiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string vendorName {
            get {
                return this.vendorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorNameField, value) != true)) {
                    this.vendorNameField = value;
                    this.RaisePropertyChanged("vendorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public string vatRegistrationNum {
            get {
                return this.vatRegistrationNumField;
            }
            set {
                if ((object.ReferenceEquals(this.vatRegistrationNumField, value) != true)) {
                    this.vatRegistrationNumField = value;
                    this.RaisePropertyChanged("vatRegistrationNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public string attributeCategory {
            get {
                return this.attributeCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.attributeCategoryField, value) != true)) {
                    this.attributeCategoryField = value;
                    this.RaisePropertyChanged("attributeCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<decimal> vendorId {
            get {
                return this.vendorIdField;
            }
            set {
                if ((this.vendorIdField.Equals(value) != true)) {
                    this.vendorIdField = value;
                    this.RaisePropertyChanged("vendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.addressLine1Field, value) != true)) {
                    this.addressLine1Field = value;
                    this.RaisePropertyChanged("addressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<System.DateTime> lastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                if ((this.lastUpdateDateField.Equals(value) != true)) {
                    this.lastUpdateDateField = value;
                    this.RaisePropertyChanged("lastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public string attribute4 {
            get {
                return this.attribute4Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute4Field, value) != true)) {
                    this.attribute4Field = value;
                    this.RaisePropertyChanged("attribute4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                if ((this.creationDateField.Equals(value) != true)) {
                    this.creationDateField = value;
                    this.RaisePropertyChanged("creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public string attribute5 {
            get {
                return this.attribute5Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute5Field, value) != true)) {
                    this.attribute5Field = value;
                    this.RaisePropertyChanged("attribute5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<System.DateTime> endDateActive {
            get {
                return this.endDateActiveField;
            }
            set {
                if ((this.endDateActiveField.Equals(value) != true)) {
                    this.endDateActiveField = value;
                    this.RaisePropertyChanged("endDateActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public string attribute6 {
            get {
                return this.attribute6Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute6Field, value) != true)) {
                    this.attribute6Field = value;
                    this.RaisePropertyChanged("attribute6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public string attribute7 {
            get {
                return this.attribute7Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute7Field, value) != true)) {
                    this.attribute7Field = value;
                    this.RaisePropertyChanged("attribute7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public string attribute8 {
            get {
                return this.attribute8Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute8Field, value) != true)) {
                    this.attribute8Field = value;
                    this.RaisePropertyChanged("attribute8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public string employeeNum {
            get {
                return this.employeeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeNumField, value) != true)) {
                    this.employeeNumField = value;
                    this.RaisePropertyChanged("employeeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public string attribute9 {
            get {
                return this.attribute9Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute9Field, value) != true)) {
                    this.attribute9Field = value;
                    this.RaisePropertyChanged("attribute9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public string attribute10 {
            get {
                return this.attribute10Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute10Field, value) != true)) {
                    this.attribute10Field = value;
                    this.RaisePropertyChanged("attribute10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public string attribute11 {
            get {
                return this.attribute11Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute11Field, value) != true)) {
                    this.attribute11Field = value;
                    this.RaisePropertyChanged("attribute11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public string attribute1 {
            get {
                return this.attribute1Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute1Field, value) != true)) {
                    this.attribute1Field = value;
                    this.RaisePropertyChanged("attribute1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public string attribute12 {
            get {
                return this.attribute12Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute12Field, value) != true)) {
                    this.attribute12Field = value;
                    this.RaisePropertyChanged("attribute12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public string attribute2 {
            get {
                return this.attribute2Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute2Field, value) != true)) {
                    this.attribute2Field = value;
                    this.RaisePropertyChanged("attribute2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public string attribute13 {
            get {
                return this.attribute13Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute13Field, value) != true)) {
                    this.attribute13Field = value;
                    this.RaisePropertyChanged("attribute13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public string attribute3 {
            get {
                return this.attribute3Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute3Field, value) != true)) {
                    this.attribute3Field = value;
                    this.RaisePropertyChanged("attribute3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public string attribute14 {
            get {
                return this.attribute14Field;
            }
            set {
                if ((object.ReferenceEquals(this.attribute14Field, value) != true)) {
                    this.attribute14Field = value;
                    this.RaisePropertyChanged("attribute14");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PovendorsRPoVendoresRecBase", Namespace="http://com/oracle/apps/povendors/POVENDORS.wsdl/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUser))]
    public partial class PovendorsRPoVendoresRecBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com/oracle/apps/povendors/POVENDORS.wsdl", ConfigurationName="VendorServices.POVENDORS")]
    public interface POVENDORS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com/oracle/apps/povendors/POVENDORS.wsdl/poVendorsWsInt", ReplyAction="*")]
        EWMS.WinService.VendorServices.poVendorsWsIntResponse poVendorsWsInt(EWMS.WinService.VendorServices.poVendorsWsIntRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://com/oracle/apps/povendors/POVENDORS.wsdl/poVendorsWsInt", ReplyAction="*")]
        System.Threading.Tasks.Task<EWMS.WinService.VendorServices.poVendorsWsIntResponse> poVendorsWsIntAsync(EWMS.WinService.VendorServices.poVendorsWsIntRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="poVendorsWsInt", WrapperNamespace="http://com/oracle/apps/povendors/POVENDORS.wsdl", IsWrapped=true)]
    public partial class poVendorsWsIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string pCompany;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pRequestDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUserArray xPoVendoresRec_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xReturnMessage_out;
        
        public poVendorsWsIntRequest() {
        }
        
        public poVendorsWsIntRequest(string pCompany, string pRequestDate, EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUserArray xPoVendoresRec_out, string xReturnMessage_out) {
            this.pCompany = pCompany;
            this.pRequestDate = pRequestDate;
            this.xPoVendoresRec_out = xPoVendoresRec_out;
            this.xReturnMessage_out = xReturnMessage_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="poVendorsWsIntResponse", WrapperNamespace="http://com/oracle/apps/povendors/POVENDORS.wsdl", IsWrapped=true)]
    public partial class poVendorsWsIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUserArray xPoVendoresRec_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xReturnMessage_out;
        
        public poVendorsWsIntResponse() {
        }
        
        public poVendorsWsIntResponse(EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUserArray xPoVendoresRec_out, string xReturnMessage_out) {
            this.xPoVendoresRec_out = xPoVendoresRec_out;
            this.xReturnMessage_out = xReturnMessage_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface POVENDORSChannel : EWMS.WinService.VendorServices.POVENDORS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class POVENDORSClient : System.ServiceModel.ClientBase<EWMS.WinService.VendorServices.POVENDORS>, EWMS.WinService.VendorServices.POVENDORS {
        
        public POVENDORSClient() {
        }
        
        public POVENDORSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public POVENDORSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POVENDORSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POVENDORSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWMS.WinService.VendorServices.poVendorsWsIntResponse EWMS.WinService.VendorServices.POVENDORS.poVendorsWsInt(EWMS.WinService.VendorServices.poVendorsWsIntRequest request) {
            return base.Channel.poVendorsWsInt(request);
        }
        
        public void poVendorsWsInt(string pCompany, string pRequestDate, ref EWMS.WinService.VendorServices.PovendorsRPoVendoresRecUserArray xPoVendoresRec_out, ref string xReturnMessage_out) {
            EWMS.WinService.VendorServices.poVendorsWsIntRequest inValue = new EWMS.WinService.VendorServices.poVendorsWsIntRequest();
            inValue.pCompany = pCompany;
            inValue.pRequestDate = pRequestDate;
            inValue.xPoVendoresRec_out = xPoVendoresRec_out;
            inValue.xReturnMessage_out = xReturnMessage_out;
            EWMS.WinService.VendorServices.poVendorsWsIntResponse retVal = ((EWMS.WinService.VendorServices.POVENDORS)(this)).poVendorsWsInt(inValue);
            xPoVendoresRec_out = retVal.xPoVendoresRec_out;
            xReturnMessage_out = retVal.xReturnMessage_out;
        }
        
        public System.Threading.Tasks.Task<EWMS.WinService.VendorServices.poVendorsWsIntResponse> poVendorsWsIntAsync(EWMS.WinService.VendorServices.poVendorsWsIntRequest request) {
            return base.Channel.poVendorsWsIntAsync(request);
        }
    }
}
